import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  date,
  jsonb,
  unique,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { showroomsTable } from "./showrooms";

/**
 * The staff master, mirrored.
 *
 * Here rather than in a module of its own because of what it is *for*: an
 * enquiry carries the employee code it was assigned to, and the dealer's system
 * will keep showing that name long after the person has left. Joining the two
 * is what turns "we are short staffed" from a feeling into a list of leads
 * nobody is working.
 *
 * That join is only possible because both sides are mirrored. Neither the
 * dealer's CRM screen nor their HR screen shows it, since each knows only half.
 */
export const dmsEmployeesTable = pgTable(
  "dms_employees",
  {
    id: serial("id").primaryKey(),
    showroomId: integer("showroom_id")
      .notNull()
      .references(() => showroomsTable.id, { onDelete: "cascade" }),
    dealerCode: text("dealer_code").notNull(),
    empCode: text("emp_code").notNull(),
    empName: text("emp_name").notNull(),
    role: text("role").notNull(),
    dateOfJoining: date("date_of_joining", { mode: "string" }),
    /** Date of leaving. Populated across a period, this is the attrition rate. */
    dateOfLeaving: date("date_of_leaving", { mode: "string" }),
    isActive: text("is_active").notNull(),
    mobileNo: text("mobile_no"),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique("dms_employees_dealer_emp_unique").on(t.dealerCode, t.empCode)],
).enableRLS();

/**
 * The enquiry mirror — where a sale starts, and where most of them stop.
 *
 * Third instance of the same pattern, and the one with a contract behind it.
 * An `OEM_PORTAL` enquiry is generated by the manufacturer, pushed to the
 * dealer, and **timed**: the industry mandate is a first response inside thirty
 * minutes, and future lead allocation depends on hitting it.
 *
 * So `firstContactAt` is the field this table exists for, and null is its most
 * important value. Nobody at a dealership is watching a thirty-minute clock on
 * a Tuesday afternoon — which is the entire thesis of this product, stated in
 * one column.
 */
export const dmsEnquiriesTable = pgTable(
  "dms_enquiries",
  {
    id: serial("id").primaryKey(),
    showroomId: integer("showroom_id")
      .notNull()
      .references(() => showroomsTable.id, { onDelete: "cascade" }),
    dealerCode: text("dealer_code").notNull(),
    enqId: text("enq_id").notNull(),

    // ── Mirror fields ───────────────────────────────────────────────────────
    /** Timestamp, not a date. The SLA is measured in minutes. */
    enquiredAt: timestamp("enquired_at", { withTimezone: true }),
    source: text("source").notNull(),
    grade: text("grade"),
    stage: text("stage").notNull(),
    customerName: text("customer_name"),
    customerMobile: text("customer_mobile"),
    modelInterest: text("model_interest"),
    assignedEmpCode: text("assigned_emp_code"),
    /** Null means nobody has made contact at all. */
    firstContactAt: timestamp("first_contact_at", { withTimezone: true }),
    lastContactDate: date("last_contact_date", { mode: "string" }),
    nextFollowUpDate: date("next_follow_up_date", { mode: "string" }),
    lostReason: text("lost_reason"),
    convertedDealId: text("converted_deal_id"),

    raw: jsonb("raw").$type<Record<string, unknown>>().notNull(),
    rawHash: text("raw_hash").notNull(),

    // ── Decision fields: ours ───────────────────────────────────────────────
    /**
     * Who actually picked this lead up after its owner left.
     *
     * The DMS cannot hold this: reassignment is a management decision, and its
     * `assigned_emp_code` will go on naming someone who no longer works here
     * until a person edits every affected record by hand. Load-bearing — an
     * orphaned lead with this set is being worked, and one without it is not.
     */
    reassignedToEmpCode: text("reassigned_to_emp_code"),
    reassignedAt: timestamp("reassigned_at", { withTimezone: true }),

    // ── Sync metadata ───────────────────────────────────────────────────────
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
    stageSince: timestamp("stage_since", { withTimezone: true }).notNull().defaultNow(),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }).notNull().defaultNow(),
    lastChangedAt: timestamp("last_changed_at", { withTimezone: true }),
    disappearedAt: timestamp("disappeared_at", { withTimezone: true }),
  },
  (t) => [
    unique("dms_enquiries_dealer_enq_unique").on(t.dealerCode, t.enqId),
    index("dms_enquiries_showroom_stage_idx").on(t.showroomId, t.stage),
  ],
).enableRLS();

export const insertDmsEnquirySchema = createInsertSchema(dmsEnquiriesTable).omit({ id: true });
export type InsertDmsEnquiry = z.infer<typeof insertDmsEnquirySchema>;
export type DmsEnquiryRow = typeof dmsEnquiriesTable.$inferSelect;
export type DmsEmployeeRow = typeof dmsEmployeesTable.$inferSelect;
